services:
  tests:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /tests
    image: playwright-tests
    volumes:
      - .:/tests
      - node_modules:/tests/node_modules
      - .test:/.test
    command: npx playwright test -u
volumes:
  node_modules: