name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  LOGIN: ${{ secrets.LOGIN }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PROXY_IP: ${{ secrets.PROXY_IP }}
  PROXY_LOGIN: ${{ secrets.PROXY_LOGIN }}
  PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}    
jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v4
      - name: Run Playwright tests inside Docker container
        run: npm run docker-compose
      
      # - uses: actions/upload-artifact@master
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: .test/output/monocart-report/
      #     retention-days: 1
      
      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 1

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages          
